### ISSUE TITLE
Learn to use Github Markdown

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#1]
From this guide: 

https://guides.github.com/features/mastering-markdown/

- Use Github issue to practice markdown. 
- Try **all features**

**Comment by biryu2205** [comment]
#1
##2
###3 
*italic*
_italic_

**Bold**
__Bold__

_**itabold** _
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)
http://mp3.zing.vn - automatic!
[mp3]([mp3.zing.vn)

**Comment by letientai299** [comment]
- Image is not displayed yet (the github logo above). 
- Italic and bold is not worked as expected. Should look like this _**italic and bold**_.
- How about ~strike through~...
- And table

Header | Header 2
---| ---
A | 123
B | 234

- Please provide an example of code fence, like the following

```java
public static void main(String[] args) {
  System.out.println("Hello world");
}
```

**Comment by biryu2205** [comment]
:(

**Comment by biryu2205** [comment]
# 1 
## 2 
### 3

**Comment by biryu2205** [comment]
![Git Icon](https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png)
![Lover](http://orig11.deviantart.net/4d38/f/2015/085/e/e/eea157e69d22ff8d3a82a09060c1c5bf-d8na0x3.jpg)

**Comment by biryu2205** [comment]
_**Boldanditalic**_

**Comment by biryu2205** [comment]
* one
* two
* Three
