### ISSUE TITLE
Complete all the Java Introduction exercies

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#10]
All 13 introduction exercies from here:

https://www.hackerrank.com/domains/java/java-introduction

Take a screenshot of the result once your done. 

Here my current status:

![image](https://user-images.githubusercontent.com/8386780/27983041-aa31f784-63dd-11e7-8b95-4f7f8300208e.png)

Page 2

![image](https://user-images.githubusercontent.com/8386780/27983046-b7bae0e6-63dd-11e7-88f1-b46306b64291.png)

You should post your result here, too.

**Comment by biryu2205** [comment]
import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner scan =new Scanner(System.in);
        int i = 0;
       
        While (scan.hasNext())
        {
         i++;
        String s = scan.nextLine();
        scan.nextLine();i

        System.out.printf("%d %s /n",i,s);

            scan.close;
         }
       
    
}
