### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#114]
This repo is useless and contains ton of crap here, due to your inability to keep up with my tasks.

- Create a new github repo, name it: `training`
- Clone the repo to your machine, then create a maven project within that repo. Commit and push source code to github.

Then, we will continue our work on the new repo.

**Comment by letientai299** [comment]
I see new repo. Wrong name. `training` with first letter in **normal case**.

**Comment by biryu2205** [comment]
I need a little time, Im reinstall some important things.Thank you.
