### ISSUE TITLE
Update project README

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#14]
- Write down your goals after our 6 months training into the README.
- Keep it short and simple.

We spend 4 days already. Keep in mine, my friend, that there's only 176 days left. And that numbers go down every fucking single day, never come back.

**Comment by biryu2205** [comment]
Can work 14 hour every day.

Master in using github.

Nothing i cant handle in java.

Can work with you .

**Comment by letientai299** [comment]
Not here. The `readme.md`, like [this one](https://github.com/letientai299/dotfiles/blob/master/readme.md).

Right now, this project is empty. You should complete #4 first, then you will have a file to update.
