### ISSUE TITLE
Fix some issues with the hackerrank projects

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#22]
Congrats. Finally see your code on github. Very nice.

I can't reopen #19, hence I create this issue to note some issues on your code.

- [ ] Java class naming is not matched with requirement. For example, with the challenge https://www.hackerrank.com/challenges/java-if-else I expect the class name is `JavaIfElse` (from underscore separated words `java-if-else` to [PascalCase](https://en.wikipedia.org/wiki/PascalCase) `JavaIfElse`). Yours is `Java3`.

- [ ] Java class is not under correct package. For introduction exercises, they should be under `hr.introduction`. For String exercises, package name should be `hr.string`. The `hr` top level package here is just for references, that our code is somehow related to HackerRank. Remember that naming and
  managing things are important for a programer.

- [ ] The top leve should be renamed from `hackerrank` to `hackerrank-java`. Who know, maybe in the future, you will have to do some task in other language, like python, ruby, C++...

There's some issues regarding your coding style, but we will talk about it later. Please fix the above issues first.

**Comment by biryu2205** [comment]
__Thank you__ for your cmt, i ll try it's again.

**Comment by letientai299** [comment]
You're not done yet.

- Folder name is still `hackerrank`, not `hackerrank-java`.
- Wrong package names. Sould be `hr.introduction` and `hr.string`.
