### ISSUE TITLE
Improve your typing speed and accuracy

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#23]
- [x] First, play 10 games on http://play.typeracer.com/ and report your current average speed and accuracy here. Keep in mind that your should try for maximum accuracy, not speed. Prevent error is better than fixing them.
- [x] Everyday, practice your typeracer about 10 games, try to improve your typing skill. You can use that site to relax if you feel overload, or need to do some action, beside reading. Don't play too much. Don't lose your focus on task. 10 games per day is OK.

You **can only close this issue** when your typing speed is more than **45WPM** and accuracy is **90%** and up.

**Try for accuracy**, not speed. Speed will auto follow once you get comfortable with the keyboard.

**Comment by biryu2205** [comment]
:v :v :v :v
