### ISSUE TITLE
[Java Basic] Revitsit Object-Oriented Programming Concepts and do the exercises

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#27]
Info
----
Link: https://docs.oracle.com/javase/tutorial/java/concepts/index.html
Exercises link: https://docs.oracle.com/javase/tutorial/java/concepts/QandE/questions.html

Goal
----
Read the link, and complete the exercises.

How to close this issue
-----------------------
- [x] For the Questions, reply in the github comment you answers
- [x] For the Exercises, reply in the github comment the code for your custom classes and interfaces.

Note
----
- Use Intellij to prototype, to ensure that your code has **valid syntax** and **good format**.
- Don't need to make the code runnable, just focus on the concept.
- Code should be posted in **Github Comment** for this issue, with markdown highlighting. Don't push to the repo.
- You are expected to complete this issue within **1 hour**. If you need more than that, report here your problems immediately. All question are welcome.

Additional info
---------------
This is a part of: https://docs.oracle.com/javase/tutorial/java/TOC.html
You will need to go through this tutorial to learn Java basic.

**Comment by biryu2205** [comment]
Real-world objects contain __behavior__ and __state__.
A software object's state is stored in  __fields__.
A software object's behavior is exposed through __Methods__.
Hiding internal data from the outside world, and accessing it only through publicly exposed methods is known as data __encapsulation__.
A blueprint for a software object is called a _class__.
Common behavior can be defined in a __superclass__ and inherited into a __subclass__ using the __extends__ keyword.
A collection of methods with no implementation is called an __interface__.
A namespace that organizes classes and interfaces by functionality is called a __package__.
The term API stands for __Application Programming Interface__?
Exercises

**Comment by biryu2205** [comment]
```java
class Bicycle {

  int cadence = 0;
  int speed = 0;
  int gear = 1;

  void changeCadence(int newValue) {
    cadence = newValue;
  }

  void changeGear(int newValue) {
    gear = newValue;
  }

  void speedUp(int increment) {
    speed = speed + increment;
  }

  void applyBrakes(int decrement) {
    speed = speed - decrement;
  }

  void printStates() {
    System.out.println("cadence:" +
        cadence + " speed:" +
        speed + " gear:" + gear);
  }

  public static void main(String[] args) {
    //sample objects
    Bicycle bike1 = new Bicycle();
    Bicycle bike2 = new Bicycle();
    // Invoke methods on objects
    bike1.changeCadence(50);
    bike1.speedUp(10);
    bike1.changeGear(2);
    bike1.printStates();

    bike2.changeCadence(50);
    bike2.speedUp(10);
    bike2.changeGear(2);
    bike2.changeCadence(40);
    bike2.speedUp(10);
    bike2.changeGear(3);
    bike2.printStates();
  }
}
class MountainBike extends Bicycle {

  // new fields and methods defining
  // a mountain bike would go here
  String specialis ="ClimbMountain";
}
```

**Comment by letientai299** [comment]
- `Bicycle` above basically copy from Oracle tutorial. Not acceptable, but
- `MountainBike` is a good example of inheritance, eventhough, too simple.
- Where is required interfaces (as specified Ex 2).

Suggestion
----------
- Try again with another class, here how, for example:

```java
interface LolChampion {
  void q();
  void w();
  void e();
  void r();
}

abstract class TankChamp implement LolChampion {
  void q() {...} // abtract implemnetation
  void w() {...}
  void e() {...}
  void r() {...}
}

class Garen extends TankChamp {
  void q() { System.out.println("Demacia"); } // concrete implemnetation
  void w() {...}
  void e() {...}
  void r() {...}
}

// Another tanks
class Amumu extends TankChamp {
  void q() { System.out.println("Demacia"); } // concrete implemnetation
  void w() {...}
  void e() {...}
  void r() {...}
  void amumuHiddenSkill(); // only Amumu has his hiden skills, Garen and other TankChamps doesn't have
}
```

Now pick another idea, and try the 2 exercises again.

**Comment by letientai299** [comment]
f*ck. Where your code for interface and abstract class?
