### ISSUE TITLE
[Java Basic] Lesson: Language Basics - Variables

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#28]
Link
----
Doc: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html
Ex: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/QandE/questions_variables.html

Note
----
- Refer to issue #27 for general notes about how to complete this issue.
- For exercises that ask you to write illegal/invalid code, and see the compiler error, you have to post that invalid/illegal code together witht he  compiler error as text. See example below.

**Code**

```java
// In file ExercisesVariable.java
public class ExercisesVariable {
  // Illegal field name because it starts with a number
  int 0anInt;
}
```

**Compiler Error**
```bash
› # note that I use the `javac` (java compiler) command line tool to compile the above code
› # You should have it installed already. (check `javac -version`)
› javac ExercisesVariable.java
ExercisesVariable.java:3: error: <identifier> expected
  int 0anInt;
     ^
ExercisesVariable.java:3: error: <identifier> expected
  int 0anInt;
            ^
2 errors
```

**Comment by biryu2205** [comment]
Question 
1.The term "instance variable" is another name for __none static fields__.
   2. The term "class variable" is another name for __static fields __.
    3.A local variable stores temporary state; it is declared inside a__between the opening and closing braces of a method__.
    4.A variable declared within the opening and closing parenthesis of a method signature is called a __parameters___.
    5.What are the eight primitive data types supported by the Java programming language?
__Byte Short Int Long Float Double Boolean Char__
    6.Character strings are represented by the class __java.lang.string__.
7.    An __Array__ is a container object that holds a fixed number of values of a single type.

**Comment by letientai299** [comment]
Please correct your markdown typo

**Comment by letientai299** [comment]
Answers are good over all. Just minor issue, primitive type in java start
with _lower case_ letter, `int`, not `Int`. And Long, Byte, Float, Double
are valid object type. That error won't be catch by compiler and will lead
to very bad performance in some cases.

**Comment by biryu2205** [comment]
```
public class sample {
^
Solution.java:15: error: <identifier> expected
  int 2Int;
     ^
Solution.java:15: error: <identifier> expected
  int 2Int;
          ^
