### ISSUE TITLE
[Java Basic] Lesson: Language Basics - Operators

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#29]
Link
----
Doc: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html
Ex: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/QandE/questions_operators.html

Note
----
- Refer to issue #27 for general notes about how to complete this issue.

**Comment by biryu2205** [comment]
1. >,+ 
2.
  2a. i=11,n=0.
  2b. i=11,n=1.
3.The logical complement operator "!" .
4.== operator is used for comparison,=! is used for assignment.
5.if somecondition = true, result = value1,else value 2

**Comment by biryu2205** [comment]
Excercises
__1__
```java
class ArithmeticDemo {

  public static void main (String[] args){
    int result = 3;
    System.out.println(result);

    result += 1; // result is now 4
     System.out.println(result);

     result /=4; // result is now 1
     System.out.println(result);

     result += 9; // result is now 9
     System.out.println(result);

      result  %= 7; // result is now 2
      System.out.println(result);
  }
}
```
__2__
```java
class PrePostDemo {
  public static void main(String[] args){
      int i = 3;
      i++;
      System.out.println(i);    // =4
      ++i;                     
      System.out.println(i);    // =5
      System.out.println(++i);  // =6
      System.out.println(i++);  // =6
      System.out.println(i);    // =7
  }
}
```

**Comment by letientai299** [comment]
Ex 1 is done well. But, Ex 2 require you to explain why 6 is printed twice, here's only code. Please explain that by your understanding about `++` and `--`

**Comment by biryu2205** [comment]
++ mean +1 ,-- mean -1 with value number type

**Comment by letientai299** [comment]
So, what is the different between `++i`, and `i++`. 

**Hint** both of them are **expressions**.
