### ISSUE TITLE
 [Java Basic] Lesson: Language Basics - Control Flow Statements

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#31]
Link
----
Doc: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/flow.html
Ex: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/QandE/questions_flow.html

Note
----
- Refer to issue #27 for general notes about how to complete this issue.

**Comment by biryu2205** [comment]
im working on this

**Comment by letientai299** [comment]
Almost 1 hour. What is the status now?

**Comment by biryu2205** [comment]
The most basic control flow statement supported by the Java programming language is the __if-then__ statement.
The __switch__ statement allows for any number of possible execution paths.
The __do while__ statement is similar to the while statement, but evaluates its expression at the __bottom___ of the loop.
How do you write an infinite loop using the for statement?
For ( ; ; )//make the condition always true 
{ anything...}
How do you write an infinite loop using the while statement?
while(//something always true){anything....}

**Comment by letientai299** [comment]
Just edit your comment for better code formatting.

**Comment by biryu2205** [comment]
Exercises
Consider the following code snippet.
if (aNumber >= 0)
    if (aNumber == 0)
        System.out.println("first string");
else System.out.println("second string");
System.out.println("third string");
a) b)Systemout nothing,error syntax.
c)d)e)
```aNumber=3
if(aNumber>=0){
     System.out.println("fisrt string");
else if (aNumber==0){
     System.out.println("secound string");
else {System.out.println("third string");
```
out put : ```fist string```
c)

**Comment by letientai299** [comment]
Reopen due to wrong conclusion for (a) and (b). Also, please make separate code for (c) and (d).
