### ISSUE TITLE
Understand some concepts about code

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#32]
For each of following concepts, try to explain its mean using plain English and give some examples.

- statement
- declaration
- initialization
- comment
- expression

**Comment by biryu2205** [comment]
1.statement:"forms a complete command to be executed and can include one or more expressions".
2.declaration:" declare a variable by specifying its data type and name".
  ex: 
```java
int number;
String s;
```
3.initialization :" to initialize a variable. It can be done at the time of declaration".
  ex:
```java
class ex{
  public int number;
  private String s;
}
```
4.comment:cmt :|
ex:
```java
   System.out.println("hello");//print hello
```
5.expression:is a series of variables, operators, and method calls.
ex:
 ```java
int number =0;
```

**Comment by letientai299** [comment]
Reopen due to misunderstanding about initialization and expression. Also, class `ex` above should have capitalized `E`.

Initialization
--------------
Initialization is "give value to the variable".

```java
int a; // this is just a declaration.
a = 10; // now we initializing it.

int b = 20; // we do both declaration and initialization as the same time.

int c; // declare, but not initialize yet
// do something dangerous with the variable, for example, invert it
System.out.println(1/c); // guess what will happen
```
One thing to remember: **Initialization should be done as near Declaration as possible**.


Expression
----------
Series of variables, operators, and method calls that **evaluates to a single value**.

Some expressions
- `2 * a`
- `4 + a`
- `fibonaci(1)` with function `int fibonaci(int index)` return  the Fn number in Fibonaci serie.

And the follow are not expression:
- `log("something")` with function `void log(String message)` return nothing but log a statement into stdout.
- `if(true){a = 2} else {a = 3}`, a completely valid *statement*, but not an expression.

See the different?


Your turn
---------

Give more example about Initialization and Expression, then you can close this issue.

**Comment by biryu2205** [comment]
```java 
int c;
System.out.println(1/c);
```
well we will get a mess like this if we dont initialzatlizing variable c yet.
error: variable c might not have been initialized
More ex for Initialization and Expression
Initiallization:
int c = 10;
Long d = 12;
Expression

**Comment by letientai299** [comment]
Format code! F*ck.
