### ISSUE TITLE
Simple exercies - triangle 1

### ISSUE THREAD

**Issue by letientai299** [biryu2205/Biryu#44]
```
0
01
012
0123
01234
012345
0123456
01234567
012345678
0123456789
```

| Level | Quest                                     |
| ----- | -----                                     |
| 1     | Use 2 `for` loop                          |
| 2     | Use 1 `for` loop only                     |
| 3     | Use 1 `for` loop and 1 `substring` method |

**Comment by biryu2205** [comment]
/**
 * Created by thien on 23/07/2017.
 */

public class Triangle {
  public static void main(String[] args) {
    String s = "";
    for (int i = 0; i <= 9; i++) {
      s += i;
      System.out.println(s + reverse);
    }
  }
}

**Comment by biryu2205** [comment]
with 2 for loop
```java
/**
 * Created by thien on 24/07/2017.
 */
public class Triangle {
  public static void main(String[] args) {

      for (int i = 0; i <= 9; i++) {
        
        for (int j = 0; j <= i ; j++) {

        System.out.printf("%d",j);}
        System.out.println();
      }
    }
  }

**Comment by biryu2205** [comment]
With 1 for loop and 1 substring method
```java
/**
 * Created by thien on 24/07/2017.
 */
public class Triangle {
  public static void main(String[] args) {

    String n = "123456789";
    for (int i = 0; i <= 9; i++) {

      System.out.println("0" + n.substring(0, i));
    }
    System.out.println();
  }
}
```

**Comment by letientai299** [comment]
- The "2 `for` loop": Do you really need `printf` to print an `int`?
- Substring: Seriously? What's point of `"0" + ...` ? Can't you just do that with the `substring` method alone?

Please fix those points.
